// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGovgjAh18fSJZZnp8gr6hTnZfhnO0x4Y',
    appId: '1:445495637159:web:d0d9ec71035ea108331782',
    messagingSenderId: '445495637159',
    projectId: 'pixelgenius-1a374',
    authDomain: 'pixelgenius-1a374.firebaseapp.com',
    storageBucket: 'pixelgenius-1a374.appspot.com',
    measurementId: 'G-22MTCC5LKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTbE7PsMtJZIJ99XW0xJhAgpgwiniAHxg',
    appId: '1:445495637159:android:ecf37c9809c0681e331782',
    messagingSenderId: '445495637159',
    projectId: 'pixelgenius-1a374',
    storageBucket: 'pixelgenius-1a374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKWPYOM_pn1MSvtMQ_8lXMTwmkjA-Zbo',
    appId: '1:445495637159:ios:5ea68d6ba38ec3f3331782',
    messagingSenderId: '445495637159',
    projectId: 'pixelgenius-1a374',
    storageBucket: 'pixelgenius-1a374.appspot.com',
    iosBundleId: 'com.example.mobils',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKWPYOM_pn1MSvtMQ_8lXMTwmkjA-Zbo',
    appId: '1:445495637159:ios:9e35bd63f0902810331782',
    messagingSenderId: '445495637159',
    projectId: 'pixelgenius-1a374',
    storageBucket: 'pixelgenius-1a374.appspot.com',
    iosBundleId: 'com.example.mobils.RunnerTests',
  );
}
